# Numpy

NumPy es una biblioteca de analisis numerico de Python. Python no tiene por ejemplo, soporte nativo para el tratamiento de Arrays. 

Ref: https://numpy.org/doc/stable/reference/routines.array-creation.html



### Creacion basada en Parametros de Dimension


#### Array

Esto crea un array n-dimensional

In [1]:

import numpy as np
array1d = np.array([1, 2, 3])
matrix = np.array([[1, 2], [3, 4]])

print(array1d)
print(matrix)



[1 2 3]
[[1 2]
 [3 4]]


#### Matriz como Array

Interpreta la entrada como una matriz y entonces devuelve un objeto Matriz

In [2]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
m = np.asmatrix(x)
print(x[0,0])



1


#### Matriz Identidad

Una matriz identidad o unidad de orden n es una matriz cuadrada donde todos sus elementos son ceros (0) menos los elementos de la diagonal principal que son unos (1)


In [3]:
import numpy as np

rows = 6
type=int

identity = np.identity(rows, dtype=type)
print(identity)
                    

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


#### Matriz Ojo

Una matriz ojo es una matriz de identidad de cualquier dimension

In [4]:
import numpy as np

rows = 6
columns = 6
index=0 # Desplazamiento de la diagonal hacia arriba o abajo
type=int # (int, float, ...)

eye = np.eye(N=rows,M=columns, k=index, dtype=type)
print(eye)


[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


#### Matriz de Unos o de Ceros

Es una matriz donde todos sus elementos son unos o ceros

In [5]:
import numpy as np

rows = 6
columns = 5
index=0
type=int # (int, float, ...)

print("Ones:")
ones = np.ones((rows,columns), dtype=type)
print(ones)

rows = 6
type=int

# Ahora creamos una matriz de unos de la dimension de una
# matriz identidad creada previamente.

identity = np.identity(rows, dtype=type)

ones_like = np.ones_like(identity, dtype=type)
print("Ones Like:")
print(ones_like)

rows = 6
columns = 5
index=0
type=int # (int, float, ...)

print("Zeros:")
zeros = np.zeros((rows,columns), dtype=type)
print(zeros)

rows = 6
type=int

# Ahora creamos una matriz de unos de la dimension de una
# matriz identidad creada previamente.

identity = np.identity(rows, dtype=type)

zeros_like = np.zeros_like(identity, dtype=type)
print("Zeros Like:")
print(zeros_like)


Ones:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Ones Like:
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
Zeros:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Zeros Like:
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


#### Matriz Rellena con Valor X

Con estas funciones podemos crear una matriz de rango determinado y rellena con un numero determinado
Tambien podemos crear una matriz donde el rango venga determinado por otra matriz previa:




In [6]:
import numpy as np

rows = 6
columns = 5
index=0
type=int # (int, float, ...)
value = 50

print("Full:")
full = np.full((rows,columns), fill_value=value, dtype=type)
print(full)

rows = 6
type=int

# Ahora creamos una matriz rellena con el valor dado a partir 
# de la dimension de una
# matriz identidad creada previamente.

identity = np.identity(rows, dtype=type)

full_like = np.full_like(identity, fill_value=value, dtype=type)
print("Full Like:")
print(full_like)

Full:
[[50 50 50 50 50]
 [50 50 50 50 50]
 [50 50 50 50 50]
 [50 50 50 50 50]
 [50 50 50 50 50]
 [50 50 50 50 50]]
Full Like:
[[50 50 50 50 50 50]
 [50 50 50 50 50 50]
 [50 50 50 50 50 50]
 [50 50 50 50 50 50]
 [50 50 50 50 50 50]
 [50 50 50 50 50 50]]


#### Matriz Vacia

Con estas funciones creamos una matriz de la dimension especificada pero vacia. 
Es similar a ones o zeros pero realmente no la rellena con ningun valor por lo que
su ejecucion es sustancialmente mas rapida


In [7]:
import numpy as np

rows = 6
columns = 5
index=0
type=int # (int, float, ...)
value = 50

print("Empty:")
empty = np.empty((rows,columns), dtype=type)
print(empty)

rows = 6
type=int

# Ahora creamos una matriz rellena con el valor dado a partir 
# de la dimension de una
# matriz identidad creada previamente.

identity = np.identity(rows, dtype=type)

empty_like = np.empty_like(identity, dtype=type)
print("Empty Like:")
print(empty_like)

Empty:
[[8070450532247928832 8070450532247928832                  16
                    0                   0]
 [7235419174270214779 4051095836575152674 7291720516583503668
  3762248840811720759 7148394817265940835]
 [3545563488761176673 3180162803108688695 8751724873810518560
  8391088052530996592 2459013923021878369]
 [7308604897285731189 8390051504720984610 8819584575519946351
  8319104481851616290 3684542879200341865]
 [3258463419153004642 7147552564817768805 3919645949801281073
  3833746779944465459 7310575177826315298]
 [3617006442610965026 3554522292206776621 3329342349694286385
  2475348352602551603 7598542776403370028]]
Empty Like:
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


#### Matrices de Relleno Automatico

Crea un array que comienza en start, termina en stop y va de step en step 

In [8]:
import numpy as np

start=100
stop=1000
step=10
type=int # (int, float, ...)

random = np.arange(start = start , stop = stop , step = step)
print(random)


[100 110 120 130 140 150 160 170 180 190 200 210 220 230 240 250 260 270
 280 290 300 310 320 330 340 350 360 370 380 390 400 410 420 430 440 450
 460 470 480 490 500 510 520 530 540 550 560 570 580 590 600 610 620 630
 640 650 660 670 680 690 700 710 720 730 740 750 760 770 780 790 800 810
 820 830 840 850 860 870 880 890 900 910 920 930 940 950 960 970 980 990]


#### Matriz de Vandermonde

Crea la Matriz de Vandermonde a partir de un array de entrada.

El increasing es el orden de los pesos de las columnas. If True, the powers increase from left to right, if False (the default) they are reversed.

Si el increasing es False, la primera comlumna es $x^{(N-1)}$, la segunda $x^{(N-2)}$ y asi sucesivamente. Si el increasing es True, las columnas son $x^0$, $x^1$, ..., $x^{(N-1)}$.
 

In [9]:
import numpy as np

x = np.array([1, 2, 3, 5])
vander = np.vander(x, N=None, increasing=False)
print(vander)


[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]


#### Matriz Triangulo, Triangulo Superior e Inferior


#### Vector a Partir de la Diagonal de una Matriz


In [10]:
import numpy as np

rows = 6
type=int
identity = np.identity(rows, dtype=type)
selected = 2 # Es la diagonal seleccionada

diagonal = np.diag(identity, k=selected)
print(identity)
diagonal = np.diag(identity, k=selected)
print(diagonal)
diagonal = np.diag(identity, k=selected-2)
print(diagonal)


[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
[0 0 0 0]
[1 1 1 1 1 1]


#### Matriz por Aplicacion de una Funcion

Construye un array ejecutando una funcion dada sobre cada elemento
Es comun usarla con funciones inline lambda.

Muy util para manipular elementos de una matriz y obtener una matriz nueva.

In [13]:
import numpy as np

# numpy.fromfunction(function, shape, *, dtype=<class 'float'>, like=None, **kwargs)[source]

shape = (2,2)
type = int

np.fromfunction(lambda i, j: i, shape=shape, dtype=type)
np.fromfunction(lambda i, j: j, shape=shape, dtype=type)
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)




array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

#### Array Unidimensional desde una Cadena con Separador


In [14]:
import numpy as np

array= np.fromstring('1, 2', dtype=int, sep=',')
print(array)

[1 2]


#### Matriz desde un Archivo de Texto
Revisar

#### Matriz desde un Archivo 
Revisar


#### Matriz Aleatoria



In [15]:
import numpy as np
import numpy.matlib as npm

np.random.seed(123)
random = npm.rand(3,3)
print(random)




[[0.69646919 0.28613933 0.22685145]
 [0.55131477 0.71946897 0.42310646]
 [0.9807642  0.68482974 0.4809319 ]]


### Algebra Lineal


#### Multiplicacion de Matrices


In [21]:
import numpy as np
import numpy.matlib as npm

np.random.seed(123)
random1 = npm.rand(3,3)
print("Matriz A =")
print(random1)

random2 = npm.rand(3,4)
print("Matriz B =")
print(random2)

D = np.matmul(random1,random2)
print("Matriz A x B =")
print(D)



Matriz A =
[[0.69646919 0.28613933 0.22685145]
 [0.55131477 0.71946897 0.42310646]
 [0.9807642  0.68482974 0.4809319 ]]
Matriz B =
[[0.39211752 0.34317802 0.72904971 0.43857224]
 [0.0596779  0.39804426 0.73799541 0.18249173]
 [0.17545176 0.53155137 0.53182759 0.63440096]]
Matriz A x B =
[[0.32997545 0.47349223 0.83957603 0.5015849 ]
 [0.33335135 0.70048242 1.15792035 0.64150764]
 [0.50982437 0.86480927 1.47619991 0.86021538]]


#### Producto Vectorial 


In [35]:

import numpy as np

array1 = np.arange(1,11,1)
array2 = np.arange(1,21,2)
print(array1)
print(array2)

vect = np.dot(array1,array2)
print(vect)

a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
print("Matriz A:")
print(a)
print("Matriz A:")
print(b)
print("<A,B>")
vect= print(np.dot(a,b))

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19]
715
Matriz A:
[[1, 0], [0, 1]]
Matriz A:
[[4, 1], [2, 2]]
<A,B>
[[4 1]
 [2 2]]


#### Suma y Resta de Matrices

In [46]:
import numpy as np
import numpy.matlib as npm

np.random.seed(123)
random1 = npm.rand(3,3)
print("Matriz A =")
print(random1)

random2 = npm.rand(3,3)
print("Matriz B =")
print(random2)

D = np.add(random1,random2)
print("Matriz A + B =")
print(D)


D = np.subtract(random1,random2)
print("Matriz A - B =")
print(D)

Matriz A =
[[0.69646919 0.28613933 0.22685145]
 [0.55131477 0.71946897 0.42310646]
 [0.9807642  0.68482974 0.4809319 ]]
Matriz B =
[[0.39211752 0.34317802 0.72904971]
 [0.43857224 0.0596779  0.39804426]
 [0.73799541 0.18249173 0.17545176]]
Matriz A + B =
[[1.0885867  0.62931735 0.95590116]
 [0.98988701 0.77914687 0.82115072]
 [1.7187596  0.86732147 0.65638366]]
Matriz A - B =
[[ 0.30435167 -0.05703868 -0.50219825]
 [ 0.11274252  0.65979107  0.0250622 ]
 [ 0.24276879  0.50233801  0.30548015]]


#### Obtener la Suma de los Elementos de una Matriz


In [42]:
import numpy as np
import numpy.matlib as npm

np.random.seed(123)
random1 = npm.rand(3,3)
print("Matriz A =")
print(random1)

print("Suma de Elementos:")
print(np.matrix.sum(random1))

Matriz A =
[[0.69646919 0.28613933 0.22685145]
 [0.55131477 0.71946897 0.42310646]
 [0.9807642  0.68482974 0.4809319 ]]
Suma de Elementos:
5.049876011559199


#### Matriz Traspuesta



In [47]:
import numpy as np
import numpy.matlib as npm

np.random.seed(123)
random1 = npm.rand(3,3)
print("Matriz A =")
print(random1)

print("Matriz T(A)")
print(np.transpose(random1))

Matriz A =
[[0.69646919 0.28613933 0.22685145]
 [0.55131477 0.71946897 0.42310646]
 [0.9807642  0.68482974 0.4809319 ]]
Matriz T(A)
[[0.69646919 0.55131477 0.9807642 ]
 [0.28613933 0.71946897 0.68482974]
 [0.22685145 0.42310646 0.4809319 ]]


#### Matriz Inversa


In [48]:
import numpy as np
import numpy.matlib as npm

np.random.seed(123)
random1 = npm.rand(3,3)
print("Matriz A =")
print(random1)

print("Matriz Inversa I(A)")
print(np.linalg.inv(random1))

Matriz A =
[[0.69646919 0.28613933 0.22685145]
 [0.55131477 0.71946897 0.42310646]
 [0.9807642  0.68482974 0.4809319 ]]
Matriz Inversa I(A)
[[  7.37388936   2.32530266  -5.52391739]
 [ 19.63709267  14.74084246 -22.23110727]
 [-43.00008309 -25.73241835  45.00051613]]
